# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdrive', '0002_auto_20161204_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellPopularity',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='road',
            name='last_user',
        ),
        migrations.RemoveField(
            model_name='road',
            name='users',
        ),
        migrations.RemoveField(
            model_name='track',
            name='author',
        ),
        migrations.RemoveField(
            model_name='track',
            name='files',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
