# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapdrive', '0003_auto_20161204_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessResultArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processresultartifact',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapdrive.File'),
        ),
    ]
