# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdrive', '0004_auto_20161204_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='processresultartifact',
            name='seconds',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='processresultartifact',
            name='url',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
